# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: survey.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'survey.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csurvey.proto\"C\n\x06\x41nswer\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61nswer_text\x18\x03 \x01(\t\"E\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10\x61nswers_received\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t26\n\rSurveyService\x12%\n\rSubmitAnswers\x12\x07.Answer\x1a\t.Response(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'survey_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSWER']._serialized_start=16
  _globals['_ANSWER']._serialized_end=83
  _globals['_RESPONSE']._serialized_start=85
  _globals['_RESPONSE']._serialized_end=154
  _globals['_SURVEYSERVICE']._serialized_start=156
  _globals['_SURVEYSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
